/* Automatically generated by
	SmartSyntaxPluginCodeGenerator * VMMaker.oscog-cb.2117 uuid: b56c34a6-88ae-4f17-930a-fc625b7ab100
   from
	Gtk3DisplayPlugin *  uuid: nil
 */
static char __buildInfo[] = "Gtk3DisplayPlugin *  uuid: nil " __DATE__ ;



#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"			/* Configuration options */
#include "sqVirtualMachine.h"	/*  The virtual machine proxy definition */
#include "sqPlatformSpecific.h"	/* Platform specific definitions */

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
# undef EXPORT
# define EXPORT(returnType) static returnType
#endif

#include "Gtk3DisplayPlugin.h"
#include "sqMemoryAccess.h"


/*** Function Prototypes ***/
EXPORT(const char*) getModuleName(void);
EXPORT(sqInt) primitiveDisableGtk3EventHandler(void);
EXPORT(sqInt) primitiveEnableGtk3EventHandler(void);
EXPORT(sqInt) primitiveHasDisplayPlugin(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
static sqInt sqAssert(sqInt aBool);


/*** Variables ***/

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*failed)(void);
static sqInt (*pop)(sqInt nItems);
static sqInt (*stackIntegerValue)(sqInt offset);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt failed(void);
extern sqInt pop(sqInt nItems);
extern sqInt stackIntegerValue(sqInt offset);
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"Gtk3DisplayPlugin *  (i)"
#else
	"Gtk3DisplayPlugin *  (e)"
#endif
;



/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

	/* InterpreterPlugin>>#getModuleName */
EXPORT(const char*)
getModuleName(void)
{
	return moduleName;
}

	/* Gtk3DisplayPlugin>>#primitiveDisableGtk3EventHandler */
EXPORT(sqInt)
primitiveDisableGtk3EventHandler(void)
{
	disableGtk3EventHandler();
	return 0;
}

	/* Gtk3DisplayPlugin>>#primitiveEnableGtk3EventHandler: */
EXPORT(sqInt)
primitiveEnableGtk3EventHandler(void)
{
	sqInt index;

	index = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	enableGtk3EventHandler(index);
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}


/*	Just answer true, letting image know we're here */

	/* Gtk3DisplayPlugin>>#primitiveHasDisplayPlugin */
EXPORT(sqInt)
primitiveHasDisplayPlugin(void)
{
	return 1;
}


/*	Note: This is coded so that it can be run in Squeak. */

	/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter)
{
	sqInt ok;

	interpreterProxy = anInterpreter;
	ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR))
	 && ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
	if (ok) {

#if !defined(SQUEAK_BUILTIN_PLUGIN)
		failed = interpreterProxy->failed;
		pop = interpreterProxy->pop;
		stackIntegerValue = interpreterProxy->stackIntegerValue;
#endif /* !defined(SQUEAK_BUILTIN_PLUGIN) */
	}
	return ok;
}

	/* SmartSyntaxInterpreterPlugin>>#sqAssert: */
static sqInt
sqAssert(sqInt aBool)
{
	/* missing DebugCode */;
	return aBool;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "Gtk3DisplayPlugin";
void* Gtk3DisplayPlugin_exports[][3] = {
	{(void*)_m, "getModuleName", (void*)getModuleName},
	{(void*)_m, "primitiveDisableGtk3EventHandler\000\377", (void*)primitiveDisableGtk3EventHandler},
	{(void*)_m, "primitiveEnableGtk3EventHandler\000\000", (void*)primitiveEnableGtk3EventHandler},
	{(void*)_m, "primitiveHasDisplayPlugin\000\377", (void*)primitiveHasDisplayPlugin},
	{(void*)_m, "setInterpreter", (void*)setInterpreter},
	{NULL, NULL, NULL}
};

#else /* ifdef SQ_BUILTIN_PLUGIN */

signed char primitiveEnableGtk3EventHandlerAccessorDepth = 0;

#endif /* ifdef SQ_BUILTIN_PLUGIN */
